version: '3'
networks:
  proxy:
    external:
      name: nginx_proxysso

services:
  front:
    build:
      context: ./
      dockerfile: Dockerfile.front
      target: prod
    container_name: front-wallet
    tty: true
    restart: always
    networks:
      - proxy
    expose:
      - 80
    healthcheck:
      test: exit $$( curl -so /dev/null --fail http://127.0.0.1:80 && echo 0 || echo 1 )
      interval: 30s
      timeout: 1s
      retries: 1
    volumes:
      - ./front/prod/:/app
    environment:
     VIRTUAL_HOST: wallet.${DOMAIN}
     VIRTUAL_PORT: 80
     LETSENCRYPT_HOST: wallet.${DOMAIN}
     LETSENCRYPT_EMAIL: ${EMAIL}

  back:
    build:
      context: ./
      dockerfile: Dockerfile.back
    container_name: back-wallet
    tty: true
    restart: always
    networks:
      - proxy
    expose:
      - 8080
    healthcheck:
      test: exit $$( curl -so /dev/null --fail http://127.0.0.1:8080 && echo 0 || echo 1 )
      interval: 30s
      timeout: 1s
      retries: 1
    volumes:
      - ./back/src:/home/api:ro
    environment:
     VIRTUAL_HOST: api.wallet.${DOMAIN}
     VIRTUAL_PORT: 8080
     LETSENCRYPT_HOST: api.wallet.${DOMAIN}
     LETSENCRYPT_EMAIL: ${EMAIL}

  rethink:
    image: rethinkdb:latest
    container_name: rethink-sso
    restart: always
    expose:
      - 8080
      - 28015
    volumes:
      - ./db/rethink/data:/data
    command: rethinkdb --bind all -d /data
    networks:
      - proxy
    environment:
     VIRTUAL_HOST: db.wallet.${DOMAIN}
     VIRTUAL_PORT: 8080
     LETSENCRYPT_HOST: db.wallet.${DOMAIN}
     LETSENCRYPT_EMAIL: ${EMAIL}
