version: '3'
networks:
  proxy:
    external:
      name: nginx_proxysso
  dbnet:
    internal: true

services:
  front:
    build:
      context: ./front/
      dockerfile: Dockerfile.front
      target: prod
    container_name: wallet-front
    tty: true
    restart: always
    networks:
      - proxy
    expose:
      - 80
    healthcheck:
      test: exit $$( curl -so /dev/null --fail http://127.0.0.1:80 && echo 0 || echo 1 )
      interval: 30s
      timeout: 1s
      retries: 1
    volumes:
      - ./front/build/:/app
    environment:
      VIRTUAL_HOST: wallet.${DOMAIN}
      VIRTUAL_PORT: 80
      LETSENCRYPT_HOST: wallet.${DOMAIN}
      LETSENCRYPT_EMAIL: ${EMAIL}

  back:
    build:
      context: ./back/
      dockerfile: Dockerfile.back
    container_name: wallet-back
    tty: true
    restart: always
    networks:
      - proxy
      - dbnet
    expose:
      - 8080
    healthcheck:
      test: exit $$( curl -so /dev/null --fail http://127.0.0.1:8080 && echo 0 || echo 1 )
      interval: 30s
      timeout: 1s
      retries: 1
    volumes:
      - ./back/src:/home/api:ro
    environment:
     MNEMONIC: quit comfort canal slam rare dynamic drift episode hen know sugar doctor
     VIRTUAL_HOST: api.wallet.${DOMAIN}
     VIRTUAL_PORT: 8080
     LETSENCRYPT_HOST: api.wallet.${DOMAIN}
     LETSENCRYPT_EMAIL: ${EMAIL}

  scroller-account:
    build:
      context: ./scroller-account/
      dockerfile: Dockerfile.scroller
    container_name: wallet-scroller_account
    tty: true
    restart: always
    networks:
      - proxy
      - dbnet
    volumes:
      - ./scroller-account/src:/home/api:ro

  scroller:
    build:
      context: ./scroller/
      dockerfile: Dockerfile.scroller
    container_name: wallet-scroller
    tty: true
    restart: always
    networks:
      - proxy
      - dbnet
    volumes:
      - ./scroller/src:/home/api:ro

  rethink:
    image: rethinkdb:latest
    container_name: wallet-rethink
    restart: always
    expose:
      - 8080
      - 28015
    volumes:
      - ./db/rethink/data:/data
    command: rethinkdb --bind all -d /data
    networks:
      - dbnet
    environment:
     VIRTUAL_HOST: db.wallet.${DOMAIN}
     VIRTUAL_PORT: 8080
     LETSENCRYPT_HOST: db.wallet.${DOMAIN}
     LETSENCRYPT_EMAIL: ${EMAIL}
